import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from './components/Navbar'
import Footer from './components/Footer'
import ThemeChange from './components/ThemeChange'
import {ThemeProvider} from 'next-themes'

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "digitalaibled",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <body className='flex justify-center items-center '>
        <div className='lg:w-3/5 w-full'>
          <ThemeProvider>
            <Navbar />

            <div className='py-4 sm:px-7 px-10'>
              <div className='flex justify-between'>
                <h2>digitalaiblend.com</h2>
                <h2 className=''>
                  <ThemeChange />
                </h2>
              </div>
              {children}
            </div>
            <Footer />
          </ThemeProvider>
        </div>
      </body>


    </html >

  );
}
